### ISSUE TITLE
capire meglio assunzioni di CUSUM e Page Hinkley

### ISSUE THREAD

**Issue by emanueledellavalle** [quantiaconsulting/streaming-machine-learning#11]
nello [spiegare CUSUM e Page Hinkley](https://github.com/quantiaconsulting/streaming-machine-learning/blob/main/slides/2_CD.pdf) non mi ha convinto:
- che CUSUM assuma che la media sia zero, non mi sembra vero e neppure necessario. Credo che possa essere che verifichi che la **differenza dei dati osservati dalla media sia sensibilmente maggiore di zero**
- che Page Hinkley assuma solo che il processo sia gaussiano. Mi sembra che la formula preveda anche che la **media deve essere positiva**

forse in entrambe le formule `(value - x_mean)` è `|value - x_mean|`

**Comment by alessiobernardo** [comment]
Sono entrambi one sided, quindi value - x_mean dovrebbe essere sempre positivo di suo
