### ISSUE TITLE
Non parliamo di hyper parameter tuning e cross validation 

### ISSUE THREAD

**Issue by emanueledellavalle** [quantiaconsulting/streaming-machine-learning#13]
Ci sono parametri fa tarare sia per i drift detector che per gli algoritmi. Dovremmo dirlo, dovremmo spiegare cosa accade quando li si tocca e dovremmo spiegare come si fa cross validation in streaming

**Comment by alessiobernardo** [comment]
Aggiungere prequential cross validation e prequential dalyed validation a slide intro dopo prequential validation
