### ISSUE TITLE
nelle slide manca KNN con Adwin

### ISSUE THREAD

**Issue by emanueledellavalle** [quantiaconsulting/streaming-machine-learning#5]
nelle [slide](https://github.com/quantiaconsulting/streaming-machine-learning/blob/main/slides/3_Classification.pdf) illustriamo il KNN con la sliding window ma non con ADWIN (che poi invece mostriamo nei [notebook](https://github.com/quantiaconsulting/streaming-machine-learning/blob/main/notebook/3.0_Stream_Classification.ipynb))

**Comment by alessiobernardo** [comment]
Aggiunto
